CREATE TABLE IF NOT EXISTS CELULARES (
    ID VARCHAR(13) NOT NULL,
    SITE_ID VARCHAR(3) NOT NULL,
    TITLE VARCHAR(255) NULL,
    PRICE DECIMAL(20,2) NULL,
    SOLD_QUANTITY INT NULL,
    THUMBNAIL VARCHAR(255) NULL,
    PROCESS_DATE DATE NOT NULL,
    LOAD_DATE TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);